name: mzansi_innovation_hub
description: ""
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.3+110
# version: 1.1.1+97 #--- Updated version for upgrader package testing

environment:
  sdk: '>=3.5.3 <4.0.0'
  # flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_core: ^29.2.10
  syncfusion_flutter_pdfviewer: ^29.2.10
  universal_html: ^2.2.4
  file_picker: ^10.1.9
  supertokens_flutter: ^0.6.3
  http: ^1.2.1
  args: ^2.7.0
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6
  printing: ^5.13.3
  geolocator: ^14.0.1
  table_calendar: ^3.1.2
  youtube_player_iframe: ^5.2.0
  mobile_scanner: ^7.0.1
  flutter_launcher_icons: ^0.14.4
  barcode_widget: ^2.0.4 #Generate Barcodes
  url_launcher: ^6.3.1
  fl_downloader: ^2.0.2
  local_auth: ^2.3.0
  math_expressions: ^2.6.0
  ollama_dart: ^0.2.2+1
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  flutter_tts: ^4.2.3
  flutter_speed_dial: ^7.0.0 
  share_plus: ^11.0.0
  app_settings: ^6.1.1
  pwa_install: ^0.0.6
  google_mobile_ads: ^6.0.0
  gma_mediation_meta: ^1.4.1
  redacted: ^1.0.13
  custom_rating_bar: ^3.0.0
  country_code_picker: ^3.3.0
  ken_logger: ^0.0.3
  go_router: ^16.1.0
  screen_brightness: ^2.1.6
  cached_network_image: ^3.4.1
  upgrader: ^12.0.0
  screenshot: ^3.0.0
  file_saver: ^0.3.1
  provider: ^6.1.5+1
  flutter_ai_toolkit: ^0.10.0
  flutter_markdown_plus: ^1.0.5
  speech_to_text: ^7.3.0
  quick_actions: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: ^2.4.8

  build_web_compilers: ^4.1.5
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/mih_components/mih_package_components/assets/images/
    - lib/mih_components/mih_package_components/assets/fonts/
    - lib/mih_components/mih_package_components/assets/images/loyalty_cards/
    - lib/mih_components/mih_package_components/assets/images/loyalty_cards/mini/
    - lib/mih_components/mih_package_components/assets/images/app_icon/
    - lib/mih_components/mih_package_components/assets/images/splash_screen/

  fonts:
    - family: MihIcons
      fonts:
        - asset: lib/mih_components/mih_package_components/assets/fonts/Mih_Icons.ttf
        
flutter_native_splash:
  color: "#3A4454"
  image: lib/mih_components/mih_package_components/assets/images/splash_screen/mih_image_splash.png
  branding: lib/mih_components/mih_package_components/assets/images/splash_screen/mih_branding_splash.png
  image_web: lib/mih_components/mih_package_components/assets/images/splash_screen/mih_image_splash_temp.gif
  branding_web: lib/mih_components/mih_package_components/assets/images/splash_screen/mih_branding_splash_temp.gif
  branding_mode: bottom
  branding_bottom_padding: 24
  android_12:
    color: "#3A4454"
    image: lib/mih_components/mih_package_components/assets/images/splash_screen/mih_image_splash_android.png
    branding: lib/mih_components/mih_package_components/assets/images/splash_screen/mih_branding_splash.png