name: mzansi_innovation_hub
description: ""
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.15+90

environment:
  sdk: '>=3.5.3 <4.0.0'
  # flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_core: ^29.2.10
  syncfusion_flutter_pdfviewer: ^29.2.10
  universal_html: ^2.2.4
  file_picker: ^10.1.9
  supertokens_flutter: ^0.6.3
  http: ^1.2.1
  args: ^2.7.0
  gif_view: ^1.0.3
  intl: ^0.20.2
  flutter_native_splash: ^2.4.1
  printing: ^5.13.3
  geolocator: ^14.0.1
  table_calendar: ^3.1.2
  youtube_player_iframe: ^5.2.0
  mobile_scanner: ^7.0.1
  flutter_launcher_icons: ^0.14.4
  barcode_widget: ^2.0.4 #Generate Barcodes
  url_launcher: ^6.3.1
  fl_downloader: ^2.0.2
  local_auth: ^2.3.0
  math_expressions: ^2.6.0
  ollama_dart: ^0.2.2+1
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  flutter_tts: ^4.2.2
  flutter_speed_dial: ^7.0.0 
  share_plus: ^11.0.0
  app_settings: ^6.1.1
  pwa_install: ^0.0.6
  google_mobile_ads: ^6.0.0
  redacted: ^1.0.13
  custom_rating_bar: ^3.0.0
  country_code_picker: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: ^2.4.8

  build_web_compilers: ^4.1.5
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/mih_components/mih_package_components/assets/images/
    - lib/mih_components/mih_package_components/assets/fonts/
    - lib/mih_components/mih_package_components/assets/images/loyalty_cards/
    - lib/mih_components/mih_package_components/assets/images/loyalty_cards/mini/
    - lib/mih_components/mih_package_components/assets/images/app_icon/
    - lib/mih_components/mih_package_components/assets/images/splash_screen/

  fonts:
    - family: MihIcons
      fonts:
        - asset: lib/mih_components/mih_package_components/assets/fonts/Mih_Icons.ttf
flutter_native_splash:
  color: "#3A4454"
  image: lib/mih_components/mih_package_components/assets/images/logo_light.png
  branding: lib/mih_components/mih_package_components/assets/images/branding_text.png
  branding_mode: bottom
  branding_bottom_padding: 24
  android_12:
    image: lib/mih_components/mih_package_components/assets/images/splash_screen/splash_screen_icon.png
    color: "#3A4454"
    branding: lib/mih_components/mih_package_components/assets/images/branding_text.png